services:
  postgres:
    image: postgres:latest
    container_name: budget_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budgets
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:  # not needed
      test: ["CMD-SHELL", "pg_isready -U user -d budgets"]
      interval: 5s
      retries: 5

  node:
    image: node:18-alpine
    container_name: budget_node
    working_dir: /app
    volumes:
      - .:/app
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: budgets
      POSTGRES_HOST: budget_postgres  
      POSTGRES_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy  # ready
    command: sh -c "npm install && tail -f /dev/null"

volumes:
  postgres_data:
